#pragma once

// Transport selection for THIS Arduino
// ------------------------------------
// Each physical Arduino talks to the master over EITHER USB serial OR I2C. That
// choice is made here, at compile time, because an I2C slave needs to know its
// own address before it can communicate.
//
//   * Leave RATA_I2C_ADDRESS undefined  -> USB serial (the default).
//   * Define it to a 7-bit address (0x08..0x77) -> this board is an I2C slave.
//
// You normally do NOT edit this file. Use the flash helper, which sets the
// address for you from a plain number:
//
//   ./firmware/flash.sh --board uno --i2c 8      # I2C slave at address 8
//   ./firmware/flash.sh --board mega             # serial (leave I2C off)
//
// The number there must match how you create the board in Python:
//   Uno(8, link=I2CLink(bus=1))
//
// The line below is only a manual override if you flash without the helper.

// #define RATA_I2C_ADDRESS 0x08
